///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DetalleExamenModelExamen {
/*
{
  "id": 7,
  "examenTitulo": "Primer parcial cosmetologia Grupo Enero 2022",
  "published_at": "2022-03-15T19:31:17.000Z",
  "created_at": "2022-03-12T14:22:45.000Z",
  "updated_at": "2022-03-15T19:31:17.000Z",
  "curso": 6,
  "tiempo": 21
} 
*/

  int? id;
  String? examenTitulo;
  String? publishedAt;
  String? createdAt;
  String? updatedAt;
  int? curso;
  int? tiempo;

  DetalleExamenModelExamen({
    this.id,
    this.examenTitulo,
    this.publishedAt,
    this.createdAt,
    this.updatedAt,
    this.curso,
    this.tiempo,
  });
  DetalleExamenModelExamen.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    examenTitulo = json['examenTitulo']?.toString();
    publishedAt = json['published_at']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    curso = json['curso']?.toInt();
    tiempo = json['tiempo']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['examenTitulo'] = examenTitulo;
    data['published_at'] = publishedAt;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['curso'] = curso;
    data['tiempo'] = tiempo;
    return data;
  }
}

class DetalleExamenModelAlumno {
/*
{
  "id": 60,
  "username": "MARÍN SOBERANIS AMERICA OLYMPIA",
  "email": "america.soberanis@cosbiome.com",
  "provider": "local",
  "confirmed": false,
  "blocked": false,
  "role": 3,
  "created_at": "2022-01-07T15:52:21.000Z",
  "updated_at": "2022-01-07T15:52:21.000Z",
  "UsuarioFoto": "",
  "AlumnoApellidoPaterno": "MARÍN",
  "AlumnoApellidoMaterno": "SOBERANIS",
  "AlumnoNombres": "AMERICA OLYMPIA",
  "AlumnoFechaNacimiento": "",
  "AlumnoEstadoCivil": "",
  "AlumnoSexo": "",
  "AlumnoLugarDeNacimiento": "",
  "AlumnoEdad": "",
  "AlumnoEscuelaDeTransferencia": "",
  "AlumnoTipoDeSangre": "",
  "AlumnoTelefono": "",
  "AlumnoCelular": "7445879531",
  "AlumnoTelefonoDeEmergencia": "",
  "AlumnoDomicilio": "PASEO DEL CAZADOR MZA 4 LOTE 4 COLONIA CERRO DEL VENADO",
  "AlumnoCodiPostal": "39500",
  "AlumnoPais": "MEXICO",
  "AlumnoEstado": "GUERRERO",
  "AlumnoMunicipio": "ACAPULCO",
  "AlumnoRfc": "",
  "AlumnoCurp": "",
  "AlumnoMensualidad": "2100",
  "AlumnoCodigo": "3370046",
  "AlumnoPresencial": false,
  "AlumnoLinea": true,
  "AlumnoVendedor": "Abraham Cisneros",
  "AlumnoPagoStripe": "",
  "AlumnoEgresado": false,
  "AlumnoPromedio": 80,
  "AlumnoStatus": "ACTIVO"
} 
*/

  int? id;
  String? username;
  String? email;
  String? provider;
  bool? confirmed;
  bool? blocked;
  int? role;
  String? createdAt;
  String? updatedAt;
  String? UsuarioFoto;
  String? AlumnoApellidoPaterno;
  String? AlumnoApellidoMaterno;
  String? AlumnoNombres;
  String? AlumnoFechaNacimiento;
  String? AlumnoEstadoCivil;
  String? AlumnoSexo;
  String? AlumnoLugarDeNacimiento;
  String? AlumnoEdad;
  String? AlumnoEscuelaDeTransferencia;
  String? AlumnoTipoDeSangre;
  String? AlumnoTelefono;
  String? AlumnoCelular;
  String? AlumnoTelefonoDeEmergencia;
  String? AlumnoDomicilio;
  String? AlumnoCodiPostal;
  String? AlumnoPais;
  String? AlumnoEstado;
  String? AlumnoMunicipio;
  String? AlumnoRfc;
  String? AlumnoCurp;
  String? AlumnoMensualidad;
  String? AlumnoCodigo;
  bool? AlumnoPresencial;
  bool? AlumnoLinea;
  String? AlumnoVendedor;
  String? AlumnoPagoStripe;
  bool? AlumnoEgresado;
  int? AlumnoPromedio;
  String? AlumnoStatus;

  DetalleExamenModelAlumno({
    this.id,
    this.username,
    this.email,
    this.provider,
    this.confirmed,
    this.blocked,
    this.role,
    this.createdAt,
    this.updatedAt,
    this.UsuarioFoto,
    this.AlumnoApellidoPaterno,
    this.AlumnoApellidoMaterno,
    this.AlumnoNombres,
    this.AlumnoFechaNacimiento,
    this.AlumnoEstadoCivil,
    this.AlumnoSexo,
    this.AlumnoLugarDeNacimiento,
    this.AlumnoEdad,
    this.AlumnoEscuelaDeTransferencia,
    this.AlumnoTipoDeSangre,
    this.AlumnoTelefono,
    this.AlumnoCelular,
    this.AlumnoTelefonoDeEmergencia,
    this.AlumnoDomicilio,
    this.AlumnoCodiPostal,
    this.AlumnoPais,
    this.AlumnoEstado,
    this.AlumnoMunicipio,
    this.AlumnoRfc,
    this.AlumnoCurp,
    this.AlumnoMensualidad,
    this.AlumnoCodigo,
    this.AlumnoPresencial,
    this.AlumnoLinea,
    this.AlumnoVendedor,
    this.AlumnoPagoStripe,
    this.AlumnoEgresado,
    this.AlumnoPromedio,
    this.AlumnoStatus,
  });
  DetalleExamenModelAlumno.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    username = json['username']?.toString();
    email = json['email']?.toString();
    provider = json['provider']?.toString();
    confirmed = json['confirmed'];
    blocked = json['blocked'];
    role = json['role']?.toInt();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    UsuarioFoto = json['UsuarioFoto']?.toString();
    AlumnoApellidoPaterno = json['AlumnoApellidoPaterno']?.toString();
    AlumnoApellidoMaterno = json['AlumnoApellidoMaterno']?.toString();
    AlumnoNombres = json['AlumnoNombres']?.toString();
    AlumnoFechaNacimiento = json['AlumnoFechaNacimiento']?.toString();
    AlumnoEstadoCivil = json['AlumnoEstadoCivil']?.toString();
    AlumnoSexo = json['AlumnoSexo']?.toString();
    AlumnoLugarDeNacimiento = json['AlumnoLugarDeNacimiento']?.toString();
    AlumnoEdad = json['AlumnoEdad']?.toString();
    AlumnoEscuelaDeTransferencia =
        json['AlumnoEscuelaDeTransferencia']?.toString();
    AlumnoTipoDeSangre = json['AlumnoTipoDeSangre']?.toString();
    AlumnoTelefono = json['AlumnoTelefono']?.toString();
    AlumnoCelular = json['AlumnoCelular']?.toString();
    AlumnoTelefonoDeEmergencia = json['AlumnoTelefonoDeEmergencia']?.toString();
    AlumnoDomicilio = json['AlumnoDomicilio']?.toString();
    AlumnoCodiPostal = json['AlumnoCodiPostal']?.toString();
    AlumnoPais = json['AlumnoPais']?.toString();
    AlumnoEstado = json['AlumnoEstado']?.toString();
    AlumnoMunicipio = json['AlumnoMunicipio']?.toString();
    AlumnoRfc = json['AlumnoRfc']?.toString();
    AlumnoCurp = json['AlumnoCurp']?.toString();
    AlumnoMensualidad = json['AlumnoMensualidad']?.toString();
    AlumnoCodigo = json['AlumnoCodigo']?.toString();
    AlumnoPresencial = json['AlumnoPresencial'];
    AlumnoLinea = json['AlumnoLinea'];
    AlumnoVendedor = json['AlumnoVendedor']?.toString();
    AlumnoPagoStripe = json['AlumnoPagoStripe']?.toString();
    AlumnoEgresado = json['AlumnoEgresado'];
    AlumnoPromedio = json['AlumnoPromedio']?.toInt();
    AlumnoStatus = json['AlumnoStatus']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['username'] = username;
    data['email'] = email;
    data['provider'] = provider;
    data['confirmed'] = confirmed;
    data['blocked'] = blocked;
    data['role'] = role;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['UsuarioFoto'] = UsuarioFoto;
    data['AlumnoApellidoPaterno'] = AlumnoApellidoPaterno;
    data['AlumnoApellidoMaterno'] = AlumnoApellidoMaterno;
    data['AlumnoNombres'] = AlumnoNombres;
    data['AlumnoFechaNacimiento'] = AlumnoFechaNacimiento;
    data['AlumnoEstadoCivil'] = AlumnoEstadoCivil;
    data['AlumnoSexo'] = AlumnoSexo;
    data['AlumnoLugarDeNacimiento'] = AlumnoLugarDeNacimiento;
    data['AlumnoEdad'] = AlumnoEdad;
    data['AlumnoEscuelaDeTransferencia'] = AlumnoEscuelaDeTransferencia;
    data['AlumnoTipoDeSangre'] = AlumnoTipoDeSangre;
    data['AlumnoTelefono'] = AlumnoTelefono;
    data['AlumnoCelular'] = AlumnoCelular;
    data['AlumnoTelefonoDeEmergencia'] = AlumnoTelefonoDeEmergencia;
    data['AlumnoDomicilio'] = AlumnoDomicilio;
    data['AlumnoCodiPostal'] = AlumnoCodiPostal;
    data['AlumnoPais'] = AlumnoPais;
    data['AlumnoEstado'] = AlumnoEstado;
    data['AlumnoMunicipio'] = AlumnoMunicipio;
    data['AlumnoRfc'] = AlumnoRfc;
    data['AlumnoCurp'] = AlumnoCurp;
    data['AlumnoMensualidad'] = AlumnoMensualidad;
    data['AlumnoCodigo'] = AlumnoCodigo;
    data['AlumnoPresencial'] = AlumnoPresencial;
    data['AlumnoLinea'] = AlumnoLinea;
    data['AlumnoVendedor'] = AlumnoVendedor;
    data['AlumnoPagoStripe'] = AlumnoPagoStripe;
    data['AlumnoEgresado'] = AlumnoEgresado;
    data['AlumnoPromedio'] = AlumnoPromedio;
    data['AlumnoStatus'] = AlumnoStatus;
    return data;
  }
}

class DetalleExamenModel {
/*
{
  "id": 70,
  "alumno": {
    "id": 60,
    "username": "MARÍN SOBERANIS AMERICA OLYMPIA",
    "email": "america.soberanis@cosbiome.com",
    "provider": "local",
    "confirmed": false,
    "blocked": false,
    "role": 3,
    "created_at": "2022-01-07T15:52:21.000Z",
    "updated_at": "2022-01-07T15:52:21.000Z",
    "UsuarioFoto": "",
    "AlumnoApellidoPaterno": "MARÍN",
    "AlumnoApellidoMaterno": "SOBERANIS",
    "AlumnoNombres": "AMERICA OLYMPIA",
    "AlumnoFechaNacimiento": "",
    "AlumnoEstadoCivil": "",
    "AlumnoSexo": "",
    "AlumnoLugarDeNacimiento": "",
    "AlumnoEdad": "",
    "AlumnoEscuelaDeTransferencia": "",
    "AlumnoTipoDeSangre": "",
    "AlumnoTelefono": "",
    "AlumnoCelular": "7445879531",
    "AlumnoTelefonoDeEmergencia": "",
    "AlumnoDomicilio": "PASEO DEL CAZADOR MZA 4 LOTE 4 COLONIA CERRO DEL VENADO",
    "AlumnoCodiPostal": "39500",
    "AlumnoPais": "MEXICO",
    "AlumnoEstado": "GUERRERO",
    "AlumnoMunicipio": "ACAPULCO",
    "AlumnoRfc": "",
    "AlumnoCurp": "",
    "AlumnoMensualidad": "2100",
    "AlumnoCodigo": "3370046",
    "AlumnoPresencial": false,
    "AlumnoLinea": true,
    "AlumnoVendedor": "Abraham Cisneros",
    "AlumnoPagoStripe": "",
    "AlumnoEgresado": false,
    "AlumnoPromedio": 80,
    "AlumnoStatus": "ACTIVO"
  },
  "examen": {
    "id": 7,
    "examenTitulo": "Primer parcial cosmetologia Grupo Enero 2022",
    "published_at": "2022-03-15T19:31:17.000Z",
    "created_at": "2022-03-12T14:22:45.000Z",
    "updated_at": "2022-03-15T19:31:17.000Z",
    "curso": 6,
    "tiempo": 21
  },
  "calificacion": 94.44444444444444,
  "published_at": "2022-03-13T01:11:58.000Z",
  "created_at": "2022-03-13T01:11:58.000Z",
  "updated_at": "2022-03-13T01:11:58.000Z"
} 
*/

  int? id;
  DetalleExamenModelAlumno? alumno;
  DetalleExamenModelExamen? examen;
  double? calificacion;
  String? publishedAt;
  String? createdAt;
  String? updatedAt;

  DetalleExamenModel({
    this.id,
    this.alumno,
    this.examen,
    this.calificacion,
    this.publishedAt,
    this.createdAt,
    this.updatedAt,
  });
  DetalleExamenModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    alumno = (json['alumno'] != null)
        ? DetalleExamenModelAlumno.fromJson(json['alumno'])
        : null;
    examen = (json['examen'] != null)
        ? DetalleExamenModelExamen.fromJson(json['examen'])
        : null;
    calificacion = json['calificacion']?.toDouble();
    publishedAt = json['published_at']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (alumno != null) {
      data['alumno'] = alumno!.toJson();
    }
    if (examen != null) {
      data['examen'] = examen!.toJson();
    }
    data['calificacion'] = calificacion;
    data['published_at'] = publishedAt;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}
