///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TermarioModel {
/*
{
  "modulo": "1er modulo Bienvenida, higiene y bioseguridad, anatomia, lesiones dermatologicas, quimica y metodos diagnosticos",
  "clases": [
    "1.     Bienvenida e integración grupal, dar a conocer los objetivos del curso y métodos de evaluación, bioseguridad e higiene"
  ]
} 
*/

  String? modulo;
  List<String?>? clases;

  TermarioModel({
    this.modulo,
    this.clases,
  });
  TermarioModel.fromJson(Map<String, dynamic> json) {
    modulo = json['modulo']?.toString();

    if (json['clases'] != null) {
      final v = json['clases'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      clases = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['modulo'] = modulo;
    if (clases != null) {
      final v = clases;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['clases'] = arr0;
    }
    return data;
  }
}
